FROM node:18-alpine as build_nginx

WORKDIR /app

COPY ./package.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable

COPY --from=build_nginx /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

# FROM alpine

# COPY --from=build_nginx /app /app/

